version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  weather_analyzer:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: weather_db
      DB_USER: user
      DB_PASSWORD: pass
    volumes:
      - .:/app
    command: python scheduler.py

volumes:
  postgres_data:
